subdir-ccflags-y += -Werror
obj-y += fuse/

obj-y += common.o
obj-y += flowctrl.o
obj-y += pmc.o
obj-$(CONFIG_TEGRA_210_R2P) += pmc-r2p.o
obj-y += cvb.o
obj-$(CONFIG_TEGRA_BPMP_MAILMAN) += tegra-bpmp-mailman.o
